app/models/character.py
class Character :

    def __init__(self,name,status,species,origin,location,image):
        self.name = name
        self.status = status
        self.species = species
        self.origin = origin
        self.location = location
        self.image = image

    def to_json(self):
        return {
            "name": self.name,
            "status": self.status,
            "species": self.species,
            "origin": self.origin,
            "location": self.location,
            "image": self.image
        }
        

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from app.config import Config
from app.routes.character import character_router


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Bootstrap(app)

    app.register_blueprint(character_router)

    return app

app/routes/character.py
from flask import Blueprint,render_template,flash,redirect,url_for
from app.models.character import Character
from app.db import db
import requests

character_router = Blueprint("character_router",__name__)

@character_router.route("/")
def principal():
    return render_template("principal.html")

#------------------------------------------------------------
@character_router.route("/listar")
def listar():
    characters = db.coleccion_character.find()

    return render_template("listar.html", characters=characters)

#------------------------------------------------------------

@character_router.route("/perfil/<id>")
def perfil(id):
    perfi_character = db.coleccion_character.find_one({"name": id})
    return render_template("perfil.html",perfi_character=perfi_character)

#------------------------------------------------------------
url="https://rickandmortyapi.com/api/character?page="

@character_router.route("/cargar",methods=['GET', 'POST'])
def cargar_json_bd():
    for num in range(1,22):
        response=requests.get(url+str(num))

        if response.status_code==200:
            response_json=response.json()
            
            for result in response_json["results"]:
                lista_character=Character(
                result["name"],
                result["status"],
                result["species"],
                result["origin"]["name"],
                result["location"]["name"],
                result["image"]
                )

            # vamos a insertar todos los documentos en la coleccion_character
                db.coleccion_character.insert_one(lista_character.to_json())

    flash("Carga exitosa","success")

    return render_template("principal.html")
        
#------------------------------------------------------------
@character_router.route("/delete")
def eliminar_coleccion():
    db.coleccion_character.drop()
    
    flash("Eliminado correctamente","success")
    return render_template("principal.html")

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block body %}
  <div class="container">
    {% for message in get_flashed_messages(category_filter=['success']) %}
    <div class="alert alert-success alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
      {{ message }}
    </div>
    {% endfor %}
    
    {% for message in get_flashed_messages(category_filter=['error'])%}
    <div class="alert alert-danger alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    
    {% block content %} {% endblock %}
</div>

{% block scripts %} {{ super() }} {% endblock %}

{% endblock %}

app/templates/listar.html
{% extends "base.html" %}

{% block content %} 

<h1>Lista de Personajes de Rick and Morty</h1>
<a href="{{url_for('character_router.principal')}}" class="btn btn-success">Volver al inicio</a>
<div class="row" style="margin-top: 30px">
    {% for character in characters %}
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <img src="{{ character.image }}" alt="Personaje" width="200" class="mx-auto d-block">
                <h3>{{ character.name }}</h3>
                <p>{{ character.status }} - {{ character.species }}</p> 
                <p>Last know location</p>
                <h4>{{ character.location }}</h4>
                <p>First seen in</p>
                <h4>{{ character.origin }}</h4>
                <a href="{{ url_for('character_router.perfil',id=character.name)}}">Ver más</a>
            </div>

        </div>

    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/perfil.html
{% extends "base.html" %}

{% block content %} 

<h1>Perfil de {{ perfi_character.name }}</h1>
<a href="{{url_for('character_router.principal')}}" class="btn btn-success">Volver al inicio</a>
<div class="row" style="margin-top: 30px">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <img src="{{ perfi_character.image }}" alt="Personaje" width="200" class="mx-auto d-block">
                <p>{{ perfi_character.status }} - {{ perfi_character.species }}</p> 
                <p>Last know location</p>
                <h4>{{ perfi_character.location }}</h4>
                <p>First seen in</p>
                <h4>{{ perfi_character.origin }}</h4>
                <a href="{{ url_for('character_router.listar')}}">Regresar</a>
            </div>

        </div>

    </div>
    
</div>
{% endblock %}

app/templates/principal.html
{% extends "base.html" %}

{% block content %} 

<div class="container">
  <h1 class="text-center">Rick and Morty</h1>
  <div class="jumbotron text-center">
    <img src="https://indiehoy.com/wp-content/uploads/2020/06/rick-and-morty-1.jpg" alt="Personaje" width="300" class="mx-auto d-block">
    <p>
      Rick y Morty (en inglés: Rick and Morty) es una serie de televisión americana de animación para adultos creada por Justin Roiland y Dan Harmon en 2013 para Adult Swim, también se emitió en Cartoon Network. La serie sigue las desventuras de un científico, Rick Sanchez, y su fácilmente influenciable nieto, Morty, quienes pasan el tiempo entre la vida doméstica y los viajes espaciales, temporales e intergalácticos.
    </p>
    <a href="{{ url_for('character_router.cargar_json_bd')}}" class="btn btn-warning">Añadir</a>
    <a href="{{ url_for('character_router.listar')}}" class="btn btn-info">Listar</a>
    <a href="{{ url_for('character_router.eliminar_coleccion')}}" class="btn btn-danger">Eliminar</a>
  </div>
</div>

{% endblock %}